# __init__.py (repo root)

from .src.quicksize import (
    NODE_CLASS_MAPPINGS as _BASE_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _BASE_NAMES,
)

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(_BASE_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_BASE_NAMES)

